import torch
import numpy as np
from ase import Atoms
from ase.neighborlist import neighbor_list

def verify_against_ase(pos, cell, z, custom_edge_index, custom_edge_shift, cutoff=5.0):
    """
    Verifies the edges and shift vectors generated by your custom algorithm against ASE's neighbor_list function.
    """
    # 1. Build the ASE Atoms object
    # We pass pbc=[True, True, True] to ensure ASE calculates the periodic boundaries
    atoms = Atoms(numbers=z.numpy(), positions=pos.numpy(), cell=cell.numpy(), pbc=True)
    
    # 2. Get the ground truth from ASE
    # 'i' = source, 'j' = target, 'S' = shift vector
    i_ase, j_ase, S_ase = neighbor_list('ijS', atoms, cutoff)
    
    # 3. Create sets of tuples for unordered comparison
    # We format each edge as: (source, target, shift_x, shift_y, shift_z)
    ase_edges = set()
    for idx in range(len(i_ase)):
        edge = (i_ase[idx], j_ase[idx], S_ase[idx][0], S_ase[idx][1], S_ase[idx][2])
        ase_edges.add(edge)
        
    custom_edges = set()
    for idx in range(custom_edge_index.shape[1]):
        i = custom_edge_index[0, idx].item()
        j = custom_edge_index[1, idx].item()
        sx, sy, sz = custom_edge_shift[idx].tolist()
        custom_edges.add((i, j, int(sx), int(sy), int(sz)))
        
    # 4. Grade the results!
    print(f"Total Edges Found by ASE: {len(ase_edges)}")
    print(f"Total Edges Found by Algorithm: {len(custom_edges)}")
    
    missing_edges = ase_edges - custom_edges
    extra_edges = custom_edges - ase_edges
    
    if len(missing_edges) == 0 and len(extra_edges) == 0:
        print("✅ SUCCESS! The algorithm perfectly matches ASE!")
    else:
        print("❌ FAILED. Mismatch detected.")
        if len(missing_edges) > 0:
            print(f"   Missed {len(missing_edges)} edges (e.g., {list(missing_edges)[0]})")
        if len(extra_edges) > 0:
            print(f"   Found {len(extra_edges)} extra edges (e.g., {list(extra_edges)[0]})")

# To use this: 
# Call verify_against_ase(pos, cell, z, my_edge_index, my_edge_shift, cutoff=5.0)